### ISSUE TITLE
immediately disconnects after connecting

### ISSUE THREAD

**Issue by Phoenix09** [yvesf/andiodine#17]
I've tried other VPN apps and they work for me
```
--------- beginning of /dev/log/main
E/SMD     (27542): smd Interface open failed errno is 517 -1
--------- beginning of /dev/log/system
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster - setNWBoosterIndicators(false)
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 1317): checkOverflow(576), More:false, Req:false Child:2
E/Watchdog( 1065): !@Sync 1305
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster - setNWBoosterIndicators(false)
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 1317): checkOverflow(576), More:false, Req:false Child:2
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 6 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster - setNWBoosterIndicators(false)
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 1317): checkOverflow(576), More:false, Req:false Child:2
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 6 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
D/InputReader( 1065): Input event: value=1
I/InputReader( 1065): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.7877 ] when=39231333223000
I/InputDispatcher( 1065): Delivering touch to (1317): action: 0x4, toolType: 1
I/InputDispatcher( 1065): Delivering touch to (4088): action: 0x4, toolType: 1
I/InputDispatcher( 1065): Delivering touch to (26702): action: 0x0, toolType: 1
D/InputReader( 1065): Input event: value=0
I/InputReader( 1065): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=39231408505000
I/InputDispatcher( 1065): Delivering touch to (26702): action: 0x1, toolType: 1
D/ConnectivityService( 1065): prepare is called by org.xapek.andiodine
I/SpenGestureManager( 1065): setFocusWindow0
D/PointerIcon( 1065): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 1065): setMouseCustomIcon IconType is same.101
D/PointerIcon( 1065): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon( 1065): setHoveringSpenCustomIcon IconType is same.1
D/STATUSBAR-StatusBarManagerService( 1065): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
I/SurfaceFlinger(  417): id=3078 createSurf (1x1),1 flag=4, JodineMain
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/InputReader( 1065): Input event: value=1
I/InputReader( 1065): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.7878 ] when=39233031528000
I/InputDispatcher( 1065): Delivering touch to (1317): action: 0x4, toolType: 1
I/InputDispatcher( 1065): Delivering touch to (4088): action: 0x4, toolType: 1
I/InputDispatcher( 1065): Delivering touch to (26702): action: 0x0, toolType: 1
D/InputReader( 1065): Input event: value=0
I/InputReader( 1065): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=39233096080000
I/InputDispatcher( 1065): Delivering touch to (26702): action: 0x1, toolType: 1
D/FRAGMENT_LIST(26702): Call VPN Service for configuration: 1
I/SpenGestureManager( 1065): setFocusWindow21015
D/STATUSBAR-StatusBarManagerService( 1065): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/PointerIcon( 1065): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 1065): setMouseCustomIcon IconType is same.101
D/PointerIcon( 1065): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon( 1065): setHoveringSpenCustomIcon IconType is same.1
D/ConfigDatabase(26702): Selected: [IodineConfiguration name=Default]
D/VPN_SERVICE(26702): VPN Thread enter
D/VPN_SERVICE(26702): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECT
D/VPN_SERVICE(26702): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT (has extras) }
E/ViewRootImpl(26702): sendUserActionEvent() mView == null
E/iodine  (26702): Topdomain from vm: xxx.yyy.net
E/iodine  (26702): Topdomain from vm: xxx.yyy.net
I/Iodine  (26702): Opened IPv4 UDP socket
D/MAIN    (26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT flg=0x10 (has extras) }
W/InputMethodManagerService( 1065): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@439b2710 attribute=null, token = android.os.BinderProxy@436ee298
I/Iodine  (26702): Using DNS type NULL queries
D/dalvikvm(26702): GC_CONCURRENT freed 1939K, 18% free 27117K/33028K, paused 4ms+4ms, total 65ms
D/        (26702): DFactory start
D/        (26702): This is decoding
D/        (26702): onDecode : stream read 202 bytes, ptr = 0x7b57b8f0
D/        (26702): onDecode : QmageDecParseHeader call : QM
D/        (26702): Qmage parsing for decoding ok
D/        (26702): onDecode : QmageDecParseHeader 9patched image
D/        (26702): onDecode : QmageDecParseHeader 9patched image end
D/        (26702): onDecode : QmageHeader Height() 96 Width() : 78 sampleSize : 1
D/        (26702): Qmage Make Color table[4]
D/        (26702): Qmage Mae Color table end
D/        (26702): 1 to 1 Index mode decoding
D/        (26702): 1 to 1 Index mode decoding end
D/        (26702): onDecode : return true
D/VPN_SERVICE(26702): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECT
D/VPN_SERVICE(26702): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT (has extras) }
I/Iodine  (26702): Version ok, both using protocol v 0x00000502. You are user #0
D/MAIN    (26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT flg=0x10 (has extras) }
D/FRAGMENT_STATUS(26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT flg=0x10 (has extras) }
I/Iodine  (26702): Server tunnel IP is 192.0.2.1
I/Iodine  (26702): Skipping raw mode
I/Iodine  (26702): Using EDNS0 extension
D/AbsListView(26702): onDetachedFromWindow
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  417): id=3078 Removed JodineMain (11/13)
I/SurfaceFlinger(  417): id=3078 Removed JodineMain (-2/13)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
I/Iodine  (26702): Switching upstream to codec Base128
I/Iodine  (26702): Server switched upstream to codec Base128
I/Iodine  (26702): No alternative downstream codec available, using default (Raw)
I/Iodine  (26702): Switching to lazy mode for low-latency
I/Iodine  (26702): Server switched to lazy mode
I/Iodine  (26702): Autoprobing max downstream fragment size... (skip with -m fragsize)
I/Iodine  (26702): 768 ok..
I/Iodine  (26702): 1152 ok..
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 6 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
I/Iodine  (26702): .
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/SSRMv2:SIOP( 1065): SIOP:: AP = 270 (0), Delta = 0
I/Iodine  (26702): .
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): .
I/Iodine  (26702): 1344 not ok..
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 6 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
E/SMD     (27542): smd Interface open failed errno is 517 -1
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 6 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
I/Iodine  (26702): .
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): .
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): .
I/Iodine  (26702): 1248 not ok..
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): .
D/dalvikvm( 8553): GC_CONCURRENT freed 1937K, 29% free 23649K/33028K, paused 32ms+6ms, total 229ms
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 5 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 5 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x2 level=2
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): .
D/STATUSBAR-NetworkController( 1317): onSignalStrengthsChanged signalStrength=SignalStrength: 4 -1 -1 -1 -1 -1 -1 99 2147483647 2147483647 2147483647 -1 2147483647 gsm|lte 0x1 level=1
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster - setNWBoosterIndicators(false)
D/        ( 1317): DFactory start
D/        ( 1317): This is decoding
D/        ( 1317): onDecode : stream read 127 bytes, ptr = 0x7e857608
D/        ( 1317): onDecode : QmageDecParseHeader call : QM
D/        ( 1317): Qmage parsing for decoding ok
D/        ( 1317): onDecode : QmageHeader Height() 54 Width() : 54 sampleSize : 1
D/        ( 1317): Qmage Make Color table[5]
D/        ( 1317): Qmage Mae Color table end
D/        ( 1317): 1 to 1 Index mode decoding
D/        ( 1317): 1 to 1 Index mode decoding end
D/        ( 1317): onDecode : return true
D/STATUSBAR-NetworkController( 1317): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 1317): checkOverflow(576), More:false, Req:false Child:2
I/Iodine  (26702): .
I/Iodine  (26702): 1200 not ok..
I/Iodine  (26702): 1176 ok..
I/Iodine  (26702): 1188 ok..
I/Iodine  (26702): will use 1188-2=1186
E/SMD     (27542): smd Interface open failed errno is 517 -1
I/Iodine  (26702): Setting downstream fragment size to max 1186...
I/Iodine  (26702): Handshake successful, leave native code
D/VPN_SERVICE(26702): Handshake successful
D/VPN_SERVICE(26702): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED
D/VPN_SERVICE(26702): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED (has extras) }
D/VPN_SERVICE(26702): Build tunnel for configuration: ip=192.0.2.2 netbits=27 mtu=1130
D/VPN_SERVICE(26702): Set default route
D/VPN_SERVICE(26702): Build tunnel interface
D/ConnectivityService( 1065): establishVpn called
D/Tethering( 1065): interfaceAdded tun0
D/Tethering( 1065): tun0 is not a tetherable iface, ignoring
D/MAIN    (26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED flg=0x10 (has extras) }
D/FRAGMENT_STATUS(26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED flg=0x10 (has extras) }
D/Tethering( 1065): interfaceLinkStateChanged tun0, false
D/Tethering( 1065): interfaceStatusChanged tun0, false
D/Tethering( 1065): interfaceLinkStateChanged tun0, true
D/Tethering( 1065): interfaceStatusChanged tun0, true
D/Vpn     ( 1065): setting state=CONNECTING, reason=establish
D/Tethering( 1065): interfaceLinkStateChanged tun0, true
D/Tethering( 1065): interfaceStatusChanged tun0, true
D/VpnJni  ( 1065): Address added on tun0: 192.0.2.2/27
D/Vpn     ( 1065): setting state=FAILED, reason=establish
D/Tethering( 1065): interfaceLinkStateChanged tun0, false
D/Tethering( 1065): interfaceStatusChanged tun0, false
W/Netd    (  406): No subsystem found in netlink event
W/Netd    (  406): No subsystem found in netlink event
D/Tethering( 1065): interfaceRemoved tun0
E/Tethering( 1065): attempting to remove unknown iface (tun0), ignoring
D/Vpn     ( 1065): Interface removed : tun0
E/NetlinkEvent(  406): Unknown ifindex 19 in RTM_DELADDR
D/NetlinkEvent(  406): Unexpected netlink message. type=0x11
I/iptables(  406): iptables: No chain/target/match by that name.
I/iptables(  406): iptables terminated by exit(1)
E/Netd    (  406): exec() res=0, status=256 for /system/bin/iptables -t mangle -D st_mangle_POSTROUTING -p tcp -o tun0 --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
I/ip6tables(  406): ip6tables: No chain/target/match by that name.
I/ip6tables(  406): ip6tables terminated by exit(1)
E/Netd    (  406): exec() res=0, status=256 for /system/bin/ip6tables -t mangle -D st_mangle_POSTROUTING -p tcp -o tun0 --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
I/iptables(  406): iptables: No chain/target/match by that name.
I/iptables(  406): iptables terminated by exit(1)
E/Netd    (  406): exec() res=0, status=256 for /system/bin/iptables -t nat -D st_nat_POSTROUTING -o tun0 -m mark --mark 62 -j MASQUERADE
W/System.err(26702): org.xapek.andiodine.IodineVpnService$IodineVpnException: Error while creating interface, please check issue #9 at https://github.com/yvesf/andiodine/issues/9
W/System.err(26702):    at org.xapek.andiodine.IodineVpnService.runTunnel(IodineVpnService.java:327)
W/System.err(26702):    at org.xapek.andiodine.IodineVpnService.run(IodineVpnService.java:229)
W/System.err(26702):    at java.lang.Thread.run(Thread.java:841)
D/VPN_SERVICE(26702): Send status: org.xapek.andiodine.IodineVpnService.STATUS_ERROR
D/VPN_SERVICE(26702): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_ERROR (has extras) }
D/VPN_SERVICE(26702): VPN Thread exit
D/MAIN    (26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_ERROR flg=0x10 (has extras) }
D/AbsListView(26702): Get MotionRecognitionManager
D/FRAGMENT_STATUS(26702): Got intent: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_ERROR flg=0x10 (has extras) }
D/        (26702): DFactory start
D/        (26702): This is decoding
D/        (26702): onDecode : stream read 93 bytes, ptr = 0x7993ddc0
D/        (26702): onDecode : QmageDecParseHeader call : QM
D/        (26702): Qmage parsing for decoding ok
D/        (26702): onDecode : QmageDecParseHeader 9patched image
D/        (26702): onDecode : QmageDecParseHeader 9patched image end
D/        (26702): onDecode : QmageHeader Height() 75 Width() : 75 sampleSize : 1
D/        (26702): Qmage Make Color table[1]
D/        (26702): Qmage Mae Color table end
D/        (26702): 1 to 1 Index mode decoding
D/        (26702): 1 to 1 Index mode decoding end
D/        (26702): onDecode : return true
D/        (26702): DFactory start
D/        (26702): isQmage : stream is not a Qmage file
D/        (26702): DFactory start
D/        (26702): This is decoding
D/        (26702): onDecode : stream read 678 bytes, ptr = 0x7a9f32b0
D/        (26702): onDecode : QmageDecParseHeader call : QM
D/        (26702): Qmage parsing for decoding ok
D/        (26702): onDecode : QmageDecParseHeader 9patched image
D/        (26702): onDecode : QmageDecParseHeader 9patched image end
D/        (26702): onDecode : QmageHeader Height() 150 Width() : 150 sampleSize : 1
D/        (26702): Qmage Make Color table[77]
D/        (26702): Qmage Mae Color table end
D/        (26702): 1 to 1 Index mode decoding
D/        (26702): 1 to 1 Index mode decoding end
D/        (26702): onDecode : return true
I/SpenGestureManager( 1065): setFocusWindow0
D/PointerIcon( 1065): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 1065): setMouseCustomIcon IconType is same.101
D/PointerIcon( 1065): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon( 1065): setHoveringSpenCustomIcon IconType is same.1
D/STATUSBAR-StatusBarManagerService( 1065): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
I/SurfaceFlinger(  417): id=3079 createSurf (1x1),1 flag=4, JodineMain
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1317): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1317): handleKeyguardVisibilityChanged(1)
E/SMD     (27542): smd Interface open failed errno is 517 -1
```
![screen-recording_20150309-144056 mp4_snapshot_00 08_ 2015 03 09_14 44 54](https://cloud.githubusercontent.com/assets/3220224/6583690/ae14500a-c75d-11e4-81c1-ff5cc96b0fe8.png)
![screen-recording_20150309-144056 mp4_snapshot_00 09_ 2015 03 09_14 45 15](https://cloud.githubusercontent.com/assets/3220224/6583691/b23ab0b6-c75d-11e4-90af-7240ea4d7b03.png)

**Comment by yvesf** [comment]
Hi thanks for reporting,
Can you please check if changing the MTU as described in #9 on the server side changes anything for you? Thanks!

**Comment by Phoenix09** [comment]
already tried that, made no difference

**Comment by Phoenix09** [comment]
weird, just tried it again and it works
maybe I forgot to save it before
feel free to close this

**Comment by yvesf** [comment]
OK, nice. In case something breaks again, don't hesitate to put a report.
