### ISSUE TITLE
Recompile source code to run on armv7 CPU

### ISSUE THREAD

**Issue by doudoulong** [yvesf/andiodine#19]
Hi,

I could not get Andiodine work on HTC EVO Design 4G. I find the CPU of HTC EVO is armv7 and current Andiodine verion only supports armeabi x86. Will it be possible to modify and recompile the source code to make it run on ARMv7? I am not a programmer so hopefully my question makes sense.

Thanks!

**Comment by yvesf** [comment]
Hello,
as far as I know 'armeabi' is more generic than 'armeabi-v7'. Therefore 
'armeabi' should run on your 'armeabi-v7' phone.
The build on f-droid.org 
https://f-droid.org/repository/browse/?fdfilter=andiodine&fdid=org.xapek.andiodine 
contains both armeabi and x86 binaries of the native library.
Please provide more information about your actual problem, are you are 
getting a specific error message somewhere?
Kind regards,
Yves

**Comment by doudoulong** [comment]
Thanks for the quick reply.

There is no error message. After entering the server name and password
and returning back to save it, the app crashes immediately.

We just tested Andiodine on as many phones as possible. I think I was
wrong earlier. It's not the chip because Aniodine works on HTC One M8,
the processor of which is also armeabi-v7. And we found another phone
model on which it has the same problem, the Moto G 4G.

Lu

**Comment by doudoulong** [comment]
Sorry, there is an error message:

"Unfortunately, andiodine has stopped."

**Comment by yvesf** [comment]
It's neccessary to have the actual error message. You can access android system logs using the 'logcat' tool via the debug bridge (adb). See here http://developer.android.com/tools/help/logcat.html
There are also android applications like 'alogcat' https://f-droid.org/repository/browse/?fdfilter=logcat&fdid=rs.pedjaapps.alogcatroot.app that show the log on the device (seems to require root to see logs from other applications), this should work as well.

**Comment by InternetFreedom** [comment]
The error message is:
06-15 13:36:06.246  11971-11971/org.xapek.andiodine W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40ab6228)
06-15 13:36:06.266  11971-11971/org.xapek.andiodine E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at org.xapek.andiodine.FragmentList.onActivityCreated(FragmentList.java:128)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:849)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1034)
            at android.app.BackStackRecord.run(BackStackRecord.java:622)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1384)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:428)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4945)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
