### ISSUE TITLE
app crash after connect

### ISSUE THREAD

**Issue by ThomasCr** [yvesf/andiodine#20]
After connecting to my Server the app crashed.

![screenshot_2015-08-16-16-23-02](https://cloud.githubusercontent.com/assets/226670/9293673/f9d576ce-4433-11e5-9c49-59a525aa2d92.png)
![screenshot_2015-08-16-16-23-08](https://cloud.githubusercontent.com/assets/226670/9293672/f93b3910-4433-11e5-92a5-bd2c7df0ca8f.png)

Any Idea where to get more informations?

**Comment by yvesf** [comment]
If you have the android sdk installed on a computer then please post the stacktrace that you receive using 'logcat' http://developer.android.com/tools/help/logcat.html

**Comment by nightcore125** [comment]
Some problem here. Device is a HTC One Mini 2.

----------------------------
C:\WINDOWS\system32>adb logcat Iodine:V VPN_SERVICE:V AndroidRuntime:V *:S
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/VPN_SERVICE(25881): VPN Thread enter
D/VPN_SERVICE(25881): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECT
D/VPN_SERVICE(25881): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT (has extras) }
I/Iodine  (25881): Opened IPv4 UDP socket
I/Iodine  (25881): Autodetecting DNS query type (use -T to override)
I/Iodine  (25881): .
D/VPN_SERVICE(25881): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECT
D/VPN_SERVICE(25881): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECT (has extras) }
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881):
I/Iodine  (25881): Using DNS type TXT queries
I/Iodine  (25881): Version ok, both using protocol v 0x00000502. You are user #0
I/Iodine  (25881): Server tunnel IP is 10.8.0.129
I/Iodine  (25881): Skipping raw mode
I/Iodine  (25881): Using EDNS0 extension
I/Iodine  (25881): Switching upstream to codec Base128
I/Iodine  (25881): Server switched upstream to codec Base128
I/Iodine  (25881): Autodetecting downstream codec (use -O to override)
I/Iodine  (25881): Switching downstream to codec Raw
I/Iodine  (25881): Server switched downstream to codec Raw
I/Iodine  (25881): Switching to lazy mode for low-latency
I/Iodine  (25881): Server switched to lazy mode
I/Iodine  (25881): Autoprobing max downstream fragment size... (skip with -m fragsize)
I/Iodine  (25881): 768 ok..
I/Iodine  (25881): 1152 ok..
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): 1344 not ok..
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): 1248 not ok..
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): 1200 not ok..
I/Iodine  (25881): 1176 ok..
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): .
I/Iodine  (25881): 1188 not ok..
I/Iodine  (25881): will use 1176-2=1174
I/Iodine  (25881): Setting downstream fragment size to max 1174...
I/Iodine  (25881): Handshake successful, leave native code
D/VPN_SERVICE(25881): Handshake successful
D/VPN_SERVICE(25881): Send status: org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED
D/VPN_SERVICE(25881): Send: Intent { act=org.xapek.andiodine.IodineVpnService.STATUS_CONNECTED (has extras) }
D/VPN_SERVICE(25881): Build tunnel for configuration: ip=10.8.0.130 netbits=262 mtu=1130
D/VPN_SERVICE(25881): VPN Thread exit
E/AndroidRuntime(25881): FATAL EXCEPTION: org.xapek.andiodine.IodineVpnService
E/AndroidRuntime(25881): Process: org.xapek.andiodine, PID: 25881
E/AndroidRuntime(25881): java.lang.IllegalArgumentException: Bad prefixLength
E/AndroidRuntime(25881):        at android.net.VpnService$Builder.check(VpnService.java:308)
E/AndroidRuntime(25881):        at android.net.VpnService$Builder.addAddress(VpnService.java:327)
E/AndroidRuntime(25881):        at org.xapek.andiodine.IodineVpnService.runTunnel(IodineVpnService.java:314)
E/AndroidRuntime(25881):        at org.xapek.andiodine.IodineVpnService.run(IodineVpnService.java:229)
E/AndroidRuntime(25881):        at java.lang.Thread.run(Thread.java:864)

**Comment by yvesf** [comment]
Hi, can you please post the commandline with which you started the iodined server?

**Comment by nightcore125** [comment]
./iodined -f -c -P PASS 10.7.0.1 tunneldomain.de -DD
It don't crash when the "Tunnel Nameserver" in the app is not empty.
Sry for my bad english :P

**Comment by nightcore125** [comment]
The tunnel IP in the commandline was before 10.8.0.1. I changed only to 10.7.0.1.

**Comment by yvesf** [comment]
I cannot reproduce this
