### ISSUE TITLE
Cannot build andiodine 1.4

### ISSUE THREAD

**Issue by LostGamerHL** [yvesf/andiodine#40]
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderEx
eption: java.security.InvalidKeyException: EC parameters error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:18
5)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:137
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:135
)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java
559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connec
(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCo
nection.java:1348)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Htt
sURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAc
essManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException:
C parameters error
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.
ava:1024)
        at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.ja
a:239)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.
ava:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerI
pl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustMa
agerImpl.java:126)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker
java:1459)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.ja
a:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl
java:1342)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:136
)
        ... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.jav
:284)
        at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.
ava:1021)
        ... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
        at sun.security.jca.GetInstance.getService(GetInstance.java:83)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.Security.getImpl(Security.java:697)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.ja
a:199)
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.jav
:279)
        ... 30 more

**Comment by yvesf** [comment]
This looks very much like a problem with your local JRE. Try checking your local JRE (`java -version`) and maybe upgrade it.
In any case it's related to the process where gradle-wrapper tries to download the gradle distribution and not to andiodine.
You could also try to install gradle locally and not using the wrapper, but I guess it will then fail later when download the dependencies-jars.
